<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\HEI;

class HEISeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Add more HEIs from your CSV file to this array
  $heis = [
    ['hei_name' => 'Andres Bonifacio College, Inc.', 'hei_code' => '9001', 'type_of_heis' => 'Private', 'city' => 'Dipolog City', 'province' => 'Zamboanga del Norte', 'district' => '2nd District, Zamboanga del Norte'],
    ['hei_name' => 'Ateneo de Zamboanga University', 'hei_code' => '9002', 'type_of_heis' => 'Private', 'city' => 'Zamboanga City', 'province' => 'Zamboanga del Sur', 'district' => '2nd District, Zamboanga del Sur'],
    ['hei_name' => 'Basilan State College', 'hei_code' => '9003', 'type_of_heis' => 'Public', 'city' => 'Isabela City', 'province' => 'Basilan', 'district' => 'Lone District (Basilan)'],
    ['hei_name' => 'Brent Hospital and Colleges Incorporated', 'hei_code' => '9004', 'type_of_heis' => 'Private', 'city' => 'Zamboanga City', 'province' => 'Zamboanga del Sur', 'district' => '2nd District, Zamboanga del Sur'],
    ['hei_name' => 'Claret College of Isabela', 'hei_code' => '9005', 'type_of_heis' => 'Private', 'city' => 'Isabela City', 'province' => 'Basilan', 'district' => 'Lone District (Basilan)'],
    ['hei_name' => 'DMC College Foundation, Inc.', 'hei_code' => '9006', 'type_of_heis' => 'Private', 'city' => 'Dipolog City', 'province' => 'Zamboanga del Norte', 'district' => '2nd District, Zamboanga del Norte'],
    ['hei_name' => 'Dr. Aurelio Mendoza Memorial Colleges', 'hei_code' => '9008', 'type_of_heis' => 'Private', 'city' => 'Ipil', 'province' => 'Zamboanga Sibugay', 'district' => '2nd District, Zamboanga Sibugay'],
    ['hei_name' => 'Immaculate Conception Archdiocesan School', 'hei_code' => '9009', 'type_of_heis' => 'Private', 'city' => 'Zamboanga City', 'province' => 'Zamboanga del Sur', 'district' => '2nd District, Zamboanga City'],
    ['hei_name' => 'Juan S. Alano Memorial School, Inc.', 'hei_code' => '9010', 'type_of_heis' => 'Private', 'city' => 'Isabela City', 'province' => 'Basilan', 'district' => 'Lone District (Basilan)'],
    ['hei_name' => 'Jose Rizal Memorial State University - Katipunan Campus', 'hei_code' => '9012', 'type_of_heis' => 'Public', 'city' => 'Katipunan', 'province' => 'Zamboanga Del Norte', 'district' => '2nd District, Zamboanga del Norte'],
    ['hei_name' => 'Marian College, Inc.', 'hei_code' => '9014', 'type_of_heis' => 'Private', 'city' => 'Ipil', 'province' => 'Zamboanga Sibugay', 'district' => '2nd District, Zamboanga Sibugay'],
    ['hei_name' => 'Blancia Carreon College', 'hei_code' => '9016', 'type_of_heis' => 'Private', 'city' => 'Not found', 'province' => 'Not found', 'district' => 'Not found'],
    ['hei_name' => 'Philippine Advent College - Sindangan', 'hei_code' => '9017', 'type_of_heis' => 'Private', 'city' => 'Sindangan', 'province' => 'Zamboanga del Norte', 'district' => '2nd District, Zamboanga del Norte'],
    ['hei_name' => 'Pilar College of Zamboanga City, Inc', 'hei_code' => '9018', 'type_of_heis' => 'Private', 'city' => 'Zamboanga City', 'province' => 'Zamboanga del Sur', 'district' => '2nd District, Zamboanga del Sur'],
    ['hei_name' => 'Rizal Memorial Institute of Dapitan City, Inc.', 'hei_code' => '9019', 'type_of_heis' => 'Private', 'city' => 'Dapitan City', 'province' => 'Zamboanga del Norte', 'district' => 'UNKNOWN - verify'],
    ['hei_name' => 'Saint Columban College, Inc.', 'hei_code' => '9020', 'type_of_heis' => 'Private', 'city' => 'Pagadian City', 'province' => 'Zamboanga del Sur', 'district' => '1st District, Zamboanga del Sur'],
    ['hei_name' => 'St. John College of Buug Foundation, Inc.', 'hei_code' => '9021', 'type_of_heis' => 'Private', 'city' => 'Buug', 'province' => 'Zamboanga Sibugay', 'district' => '1st District, Zamboanga Sibugay'],
    ['hei_name' => 'Saint Joseph College of Sindangan Incorporated', 'hei_code' => '9022', 'type_of_heis' => 'Private', 'city' => 'Sindangan', 'province' => 'Zamboanga del Norte', 'district' => '2nd District, Zamboanga del Norte'],
    ['hei_name' => 'St. Vincent\'s College Incorporated', 'hei_code' => '9023', 'type_of_heis' => 'Private', 'city' => 'Dipolog City', 'province' => 'Zamboanga del Norte', 'district' => '2nd District, Zamboanga del Norte'],
    ['hei_name' => 'Saint Estanislao Kostka College, Inc.', 'hei_code' => '9024', 'type_of_heis' => 'Private', 'city' => 'Manukan', 'province' => 'Zamboanga Del Norte', 'district' => '2nd District, Zamboanga del Norte'],
    ['hei_name' => 'Southern Mindanao Colleges Agro-Tech', 'hei_code' => '9026', 'type_of_heis' => 'Private', 'city' => 'Dumalinao', 'province' => 'Zamboanga Del Sur', 'district' => '2nd District, Zamboanga del Sur'],
    ['hei_name' => 'Southern City Colleges, Inc.', 'hei_code' => '9027', 'type_of_heis' => 'Private', 'city' => 'Zamboanga City', 'province' => 'Zamboanga del Sur', 'district' => '2nd District, Zamboanga del Sur'],
    ['hei_name' => 'Southern Mindanao Colleges', 'hei_code' => '9028', 'type_of_heis' => 'Private', 'city' => 'Pagadian City', 'province' => 'Zamboanga del Sur', 'district' => '1st District, Zamboanga del Sur'],
    ['hei_name' => 'Southern Philippine College', 'hei_code' => '9029', 'type_of_heis' => 'Private', 'city' => 'Labason', 'province' => 'Zamboanga del Norte', 'district' => '3rd District, Zamboanga del Norte'],
    ['hei_name' => 'Western Mindanao State University', 'hei_code' => '9030', 'type_of_heis' => 'Public', 'city' => 'Zamboanga City', 'province' => 'Zamboanga del Sur', 'district' => '2nd District, Zamboanga del Sur'],
    ['hei_name' => 'Western Mindanao State University - Alicia ESU', 'hei_code' => '09030a', 'type_of_heis' => 'Public', 'city' => 'Alicia', 'province' => 'Zamboanga Sibugay', 'district' => '1st District, Zamboanga Sibugay'],
    ['hei_name' => 'Western Mindanao State University - Aurora ESU', 'hei_code' => '09030b', 'type_of_heis' => 'Public', 'city' => 'Zamboanga City', 'province' => 'Zamboanga del Sur', 'district' => '2nd District, Zamboanga del Sur'],
    ['hei_name' => 'Western Mindanao State University - Diplahan ESU', 'hei_code' => '09030c', 'type_of_heis' => 'Public', 'city' => 'Diplahan', 'province' => 'Zamboanga Sibugay', 'district' => '1st District, Zamboanga Sibugay'],
    ['hei_name' => 'Western Mindanao State University - Imelda ESU', 'hei_code' => '09030d', 'type_of_heis' => 'Public', 'city' => 'Imelda', 'province' => 'Zamboanga Sibugay', 'district' => '1st District, Zamboanga Sibugay'],
    ['hei_name' => 'Western Mindanao State University - Ipil ESU', 'hei_code' => '09030e', 'type_of_heis' => 'Public', 'city' => 'Ipil', 'province' => 'Zamboanga Sibugay', 'district' => '2nd District, Zamboanga Sibugay'],
    ['hei_name' => 'Western Mindanao State University - Mabuhay ESU', 'hei_code' => '09030f', 'type_of_heis' => 'Public', 'city' => 'Mabuhay', 'province' => 'Zamboanga Sibugay', 'district' => '1st District, Zamboanga Sibugay'],
    ['hei_name' => 'Western Mindanao State University - Malangas ESU', 'hei_code' => '09030g', 'type_of_heis' => 'Public', 'city' => 'Olutanga', 'province' => 'Zamboanga Sibugay', 'district' => '1st District, Zamboanga Sibugay'],
    ['hei_name' => 'Western Mindanao State University - Molave ESU', 'hei_code' => '09030h', 'type_of_heis' => 'Public', 'city' => 'Molave', 'province' => 'Zamboanga Del Sur', 'district' => '1st District, Zamboanga del Sur'],
    ['hei_name' => 'Western Mindanao State University - Olutanga ESU', 'hei_code' => '09030i', 'type_of_heis' => 'Public', 'city' => 'Olutanga', 'province' => 'Zamboanga Sibugay', 'district' => '1st District, Zamboanga Sibugay'],
    ['hei_name' => 'Western Mindanao State University - Pagadian ESU', 'hei_code' => '09030j', 'type_of_heis' => 'Public', 'city' => 'Pagadian City', 'province' => 'Zamboanga del Sur', 'district' => '1st District, Zamboanga del Sur'],
    ['hei_name' => 'Western Mindanao State University - Siay ESU', 'hei_code' => '09030l', 'type_of_heis' => 'Public', 'city' => 'Siay', 'province' => 'Zamboanga Sibugay', 'district' => '2nd District, Zamboanga Sibugay'],
    ['hei_name' => 'Western Mindanao State University - Tungawan ESU', 'hei_code' => '09030m', 'type_of_heis' => 'Public', 'city' => 'Tungawan', 'province' => 'Zamboanga Sibugay', 'district' => '2nd District, Zamboanga Sibugay'],
    ['hei_name' => 'Western Mindanao State University - Naga ESU', 'hei_code' => '09030n', 'type_of_heis' => 'Public', 'city' => 'Naga', 'province' => 'Zamboanga Sibugay', 'district' => '2nd District, Zamboanga Sibugay'],
    ['hei_name' => 'Western Mindanao State University - Curuan ESU', 'hei_code' => '09030o', 'type_of_heis' => 'Public', 'city' => 'Zamboanga City', 'province' => 'Zamboanga del Sur', 'district' => '2nd District, Zamboanga del Sur'],
    ['hei_name' => 'Universidad de Zamboanga', 'hei_code' => '9031', 'type_of_heis' => 'Private', 'city' => 'Zamboanga City', 'province' => 'Zamboanga del Sur', 'district' => '2nd District, Zamboanga del Sur'],
    ['hei_name' => 'Zamboanga Peninsula Polytechnic State University', 'hei_code' => '9032', 'type_of_heis' => 'Public', 'city' => 'Zamboanga City', 'province' => 'Zamboanga del Sur', 'district' => '2nd District, Zamboanga del Sur'],
    ['hei_name' => 'Zamboanga Peninsula Polytechnic State University - Kabasalan', 'hei_code' => '09032a', 'type_of_heis' => 'Public', 'city' => 'Kabasalan', 'province' => 'Zamboanga del Sur', 'district' => '2nd District, Zamboanga del Sur'],
    ['hei_name' => 'Zamboanga Peninsula Polytechnic State University - Siay', 'hei_code' => '09032b', 'type_of_heis' => 'Public', 'city' => 'Siay', 'province' => 'Zamboanga Sibugay', 'district' => '2nd District, Zamboanga Sibugay'],
    ['hei_name' => 'Zamboanga Peninsula Polytechnic State University - Vitali', 'hei_code' => '09032c', 'type_of_heis' => 'Public', 'city' => 'Vitali', 'province' => 'Zamboanga City', 'district' => '1st District, Zamboanga City'],
    ['hei_name' => 'Zamboanga State College of Marine Sciences and Technology', 'hei_code' => '9035', 'type_of_heis' => 'Public', 'city' => 'Zamboanga City', 'province' => 'Zamboanga del Sur', 'district' => '2nd District, Zamboanga del Sur'],
    ['hei_name' => 'J. H. Cerilles State College Main - Mati', 'hei_code' => '9036', 'type_of_heis' => 'Public', 'city' => 'San Miguel', 'province' => 'Zamboanga del Sur', 'district' => '2nd District, Zamboanga del Sur'],
    ['hei_name' => 'J. H. Cerilles State College - Dumingag Campus', 'hei_code' => '09036q', 'type_of_heis' => 'Public', 'city' => 'Dumingag', 'province' => 'Zamboanga del Sur', 'district' => '1st District, Zamboanga del Sur'],
    ['hei_name' => 'Medina College, Incorporated', 'hei_code' => '9041', 'type_of_heis' => 'Private', 'city' => 'Pagadian City', 'province' => 'Zamboanga del Sur', 'district' => '1st District, Zamboanga del Sur'],
    ['hei_name' => 'Pagadian Capitol College, Inc.', 'hei_code' => '9043', 'type_of_heis' => 'Private', 'city' => 'Pagadian City', 'province' => 'Zamboanga del Sur', 'district' => '1st District, Zamboanga del Sur'],
    ['hei_name' => 'Aurora Pioneers Memorial College, Inc.', 'hei_code' => '9046', 'type_of_heis' => 'Private', 'city' => 'Aurora', 'province' => 'Zamboanga del Sur', 'district' => '1st District, Zamboanga del Sur'],
    ['hei_name' => 'Dipolog City Institute of Technology', 'hei_code' => '9047', 'type_of_heis' => 'Private', 'city' => 'Dipolog City', 'province' => 'Zamboanga del Norte', 'district' => '2nd District, Zamboanga del Norte'],
    ['hei_name' => 'Jose Rizal Memorial State University', 'hei_code' => '9048', 'type_of_heis' => 'Public', 'city' => 'Dapitan City', 'province' => 'Zamboanga del Norte', 'district' => '1st District, Zamboanga del Norte'],
    ['hei_name' => 'Ebenezer Bible College and Seminary, Inc.', 'hei_code' => '9049', 'type_of_heis' => 'Private', 'city' => 'Zamboanga City', 'province' => 'Zamboanga del Sur', 'district' => '2nd District, Zamboanga del Sur'],
    ['hei_name' => 'St. Mary\'s College of Labason, Inc.', 'hei_code' => '9050', 'type_of_heis' => 'Private', 'city' => 'Labason', 'province' => 'Zamboanga del Norte', 'district' => '3rd District, Zamboanga del Norte'],
    ['hei_name' => 'J. H. Cerilles State College - Canuto M.S. Enerio Campus', 'hei_code' => '9051', 'type_of_heis' => 'Public', 'city' => 'Lakewood', 'province' => 'Zamboanga del Sur', 'district' => '2nd District, Zamboanga del Sur'],
    ['hei_name' => 'Jose Rizal Memorial State University - Dipolog Campus', 'hei_code' => '9053', 'type_of_heis' => 'Public', 'city' => 'Dipolog City', 'province' => 'Zamboanga del Norte', 'district' => '2nd District, Zamboanga del Norte'],
    ['hei_name' => 'Jose Rizal Memorial State University - Siocon Campus', 'hei_code' => '9054', 'type_of_heis' => 'Public', 'city' => 'Siocon', 'province' => 'Zambaonga Del Norte', 'district' => '3rd District, Zamboanga del Norte'],
    ['hei_name' => 'AMA Computer College - Zamboanga', 'hei_code' => '9055', 'type_of_heis' => 'Private', 'city' => 'Zamboanga City', 'province' => 'Zamboanga del Sur', 'district' => '2nd District, Zamboanga del Sur'],
    ['hei_name' => 'Colegio de San Francisco Javier of Rizal, Zamboanga del Norte, Incorporated', 'hei_code' => '9056', 'type_of_heis' => 'Private', 'city' => 'Rizal', 'province' => 'Zamboanga Del Norte', 'district' => '3rd District, Zamboanga del Norte'],
    ['hei_name' => 'Computer Technologies Institute of Zamboanga City, Inc.', 'hei_code' => '9058', 'type_of_heis' => 'Private', 'city' => 'Zamboanga City', 'province' => 'Zamboanga del Sur', 'district' => '2nd District, Zamboanga del Sur'],
    ['hei_name' => 'HMIJ Foundation - Philippine Islamic College, Inc.', 'hei_code' => '9059', 'type_of_heis' => 'Private', 'city' => 'Zamboanga City', 'province' => 'Zamboanga del Sur', 'district' => '1st District, Zamboanga City'],
    ['hei_name' => 'Mindanao State University - Buug Campus', 'hei_code' => '9060', 'type_of_heis' => 'Public', 'city' => 'Buug', 'province' => 'Zamboanga Sibugay', 'district' => '1st District, Zamboanga Sibugay'],
    ['hei_name' => 'Eastern Mindanao College of Technology', 'hei_code' => '9061', 'type_of_heis' => 'Private', 'city' => 'Pagadian City', 'province' => 'Zamboanga del Sur', 'district' => '1st District, Zamboanga del Sur'],
    ['hei_name' => 'Universidad de Zamboanga - Ipil', 'hei_code' => '9062', 'type_of_heis' => 'Private', 'city' => 'Ipil', 'province' => 'Zamboanga Sibugay', 'district' => '2nd District, Zamboanga Sibugay'],
    ['hei_name' => 'Medina College Ipil, Inc.', 'hei_code' => '9065', 'type_of_heis' => 'Private', 'city' => 'Ipil', 'province' => 'Zamboanga Sibugay', 'district' => '2nd District, Zamboanga Sibugay'],
    ['hei_name' => 'Philippine Technological and Marine Sciences', 'hei_code' => '9068', 'type_of_heis' => 'Private', 'city' => 'Pagadian City', 'province' => 'Zamboanga del Sur', 'district' => '1st District, Zamboanga del Sur'],
    ['hei_name' => 'Southern Peninsula College, Inc.', 'hei_code' => '9070', 'type_of_heis' => 'Private', 'city' => 'Labason', 'province' => 'Zamboanga del Norte', 'district' => '3rd District, Zamboanga del Norte'],
    ['hei_name' => 'Lucan Central Colleges, Inc.', 'hei_code' => '9071', 'type_of_heis' => 'Private', 'city' => 'Pagadian City', 'province' => 'Zamboanga del Sur', 'district' => '1st District, Zamboanga del Sur'],
    ['hei_name' => 'Sibugay Technical Institute Inc.', 'hei_code' => '9072', 'type_of_heis' => 'Private', 'city' => 'Ipil', 'province' => 'Zamboanga Sibugay', 'district' => '2nd District, Zamboanga Sibugay'],
    ['hei_name' => 'Universidad de Zamboanga - Pagadian Branch Inc.', 'hei_code' => '9074', 'type_of_heis' => 'Private', 'city' => 'Pagadian City', 'province' => 'Zamboanga del Sur', 'district' => '1st District, Zamboanga del Sur'],
    ['hei_name' => 'Aim High Colleges, Inc.', 'hei_code' => '9076', 'type_of_heis' => 'Private', 'city' => 'Ipil', 'province' => 'Zamboanga Sibugay', 'district' => '2nd District, Zamboanga Sibugay'],
    ['hei_name' => 'Ave Maria College', 'hei_code' => '9077', 'type_of_heis' => 'Private', 'city' => 'Liloy', 'province' => 'Zamboanga Del Norte', 'district' => '3rd District, Zamboanga del Norte'],
    ['hei_name' => 'Hyrons College Philippines, Inc.', 'hei_code' => '9079', 'type_of_heis' => 'Private', 'city' => 'Tukuran', 'province' => 'Zamboanga del Sur', 'district' => '1st District, Zamboanga del Sur'],
    ['hei_name' => 'Jose Rizal Memorial State University - Tampilisan Campus', 'hei_code' => '9081', 'type_of_heis' => 'Public', 'city' => 'Tampilisan', 'province' => 'Zamboanga del Norte', 'district' => '3rd District, Zamboanga del Norte'],
    ['hei_name' => 'Nuevo Zamboanga College, Inc.', 'hei_code' => '9083', 'type_of_heis' => 'Private', 'city' => 'Zamboanga City', 'province' => 'Zamboanga del Sur', 'district' => '2nd District, Zamboanga del Sur'],
    ['hei_name' => 'Philippine Advent College - Salug Campus', 'hei_code' => '9085', 'type_of_heis' => 'Private', 'city' => 'Salug', 'province' => 'Zamboanga del Norte', 'district' => '3rd District, Zamboanga del Norte'],
    ['hei_name' => 'Yllana Bay View College, Inc.', 'hei_code' => '9087', 'type_of_heis' => 'Private', 'city' => 'Pagadian City', 'province' => 'Zamboanga del Sur', 'district' => '1st District, Zamboanga del Sur'],
    ['hei_name' => 'Alhadeetha Mindanao College, Inc.', 'hei_code' => '9089', 'type_of_heis' => 'Private', 'city' => 'Labangan', 'province' => 'Zamboanga del Sur', 'district' => '1st District, Zamboanga del Sur'],
    ['hei_name' => 'Zamboanga del Sur Provincial Government College - Aurora', 'hei_code' => '9090', 'type_of_heis' => 'Public', 'city' => 'Aurora', 'province' => 'Zamboanga Del Sur', 'district' => '1st District, Zamboanga del Sur'],
    ['hei_name' => 'Southern City Colleges - West Campus', 'hei_code' => '9094', 'type_of_heis' => 'Private', 'city' => 'Zamboanga City', 'province' => 'Zamboanga del Sur', 'district' => '2nd District, Zamboanga del Sur'],
    ['hei_name' => 'ZAMSULA Everlasting College', 'hei_code' => '9095', 'type_of_heis' => 'Private', 'city' => 'Salug', 'province' => 'Zamboanga del Norte', 'district' => '3rd District, Zamboanga del Norte</SHEET></DOCUMENT>'],
    ['hei_name' => 'Our Lady of Triumph Institute of Technology, Inc.', 'hei_code' => '9096', 'type_of_heis' => 'Private', 'city' => 'Pagadian City', 'province' => 'Zamboanga del Sur', 'district' => '1st District, Zamboanga del Sur'],
    ['hei_name' => 'West Prime Horizon Institute, Inc.', 'hei_code' => '9097', 'type_of_heis' => 'Private', 'city' => 'Pagadian City', 'province' => 'Zamboanga del Sur', 'district' => '1st District, Zamboanga del Sur'],
    ['hei_name' => 'Colegio de la Ciudad de Zamboanga', 'hei_code' => '9098', 'type_of_heis' => 'Private', 'city' => 'Zamboanga City', 'province' => 'Zamboanga del Sur', 'district' => '2nd District, Zamboanga del Sur'],
    ['hei_name' => 'Zamboanga del Sur Provincial Government College - Pagadian', 'hei_code' => '9099', 'type_of_heis' => 'Public', 'city' => 'Pagadian City', 'province' => 'Zamboanga del Sur', 'district' => '1st District, Zamboanga del Sur'],
    ['hei_name' => 'Ferndale College - Zamboanga Peninsula, Inc.', 'hei_code' => '9100', 'type_of_heis' => 'Private', 'city' => 'Zamboanga City', 'province' => 'Zamboanga del Sur', 'district' => '2nd District, Zamboanga del Sur'],
    ['hei_name' => 'Metro Zampen College, Inc.', 'hei_code' => '9101', 'type_of_heis' => 'Private', 'city' => 'Zamboanga City', 'province' => 'Zamboanga del Sur', 'district' => '2nd District, Zamboanga del Sur'],
    ['hei_name' => 'Emmaus College of Theology Foundation, Inc.', 'hei_code' => '9102', 'type_of_heis' => 'Private', 'city' => 'Zamboanga City', 'province' => 'Zambaonga del Sur', 'district' => 'UNKNOWN - verify'],
    ['hei_name' => 'Pagadian City International College', 'hei_code' => '9103', 'type_of_heis' => 'Private', 'city' => 'Pagadian City', 'province' => 'Zamboanga del Sur', 'district' => '1st District, Zamboanga del Sur'],
    ['hei_name' => 'Philippine Advent College - Leon B. Postigo Campus', 'hei_code' => '9104', 'type_of_heis' => 'Private', 'city' => 'Leon B. Postigo', 'province' => 'Zamboanga del Norte', 'district' => 'UNKNOWN - verify'],
    ['hei_name' => 'Zamboanga del Sur Provincial Government College - Dimataling', 'hei_code' => '9105', 'type_of_heis' => 'Public', 'city' => 'Dimataling', 'province' => 'Zamboanga del Sur', 'district' => '2nd District, Zamboanga del Sur'],
    ['hei_name' => 'Helping Hands College and Wellness Center, Inc.', 'hei_code' => '9106', 'type_of_heis' => 'Private', 'city' => 'Leon Postigo', 'province' => 'Zamboanga del Norte', 'district' => '1st District, Zamboanga City'],
    ['hei_name' => 'Central Sulu College', 'hei_code' => '15002', 'type_of_heis' => 'Private', 'city' => '', 'province' => 'Sulu', 'district' => 'Sulu (1st/2nd) - verify'],
    ['hei_name' => 'Hadji Butu School of Arts and Trades', 'hei_code' => '15003', 'type_of_heis' => 'Private', 'city' => 'Not found', 'province' => 'Not found', 'district' => 'Not found'],
    ['hei_name' => 'Lapak Agricultural School', 'hei_code' => '15005', 'type_of_heis' => 'Private', 'city' => 'Sulu', 'province' => '', 'district' => 'UNKNOWN - verify'],
    ['hei_name' => 'Mindanao State University - Sulu Development Technical College', 'hei_code' => '15007', 'type_of_heis' => 'Public', 'city' => 'Sulu', 'province' => '', 'district' => 'UNKNOWN - verify'],
    ['hei_name' => 'Notre Dame Jolo College', 'hei_code' => '15009', 'type_of_heis' => 'Private', 'city' => '', 'province' => 'Sulu', 'district' => 'Sulu (1st/2nd) - verify'],
    ['hei_name' => 'Sulu State College', 'hei_code' => '15013', 'type_of_heis' => 'Public', 'city' => 'Patikul', 'province' => 'Sulu', 'district' => '1st/2nd District (Sulu) - verify'],
    ['hei_name' => 'Tawi-Tawi Regional Agricultural College', 'hei_code' => '15014', 'type_of_heis' => 'Public', 'city' => 'Bongao', 'province' => 'Tawi-Tawi', 'district' => 'Lone District (Tawi-Tawi)'],
    ['hei_name' => 'Southwestern Mindanao Islamic Institute', 'hei_code' => '15025', 'type_of_heis' => 'Private', 'city' => 'Sulu', 'province' => '', 'district' => 'UNKNOWN - verify'],
    ['hei_name' => 'Mindanao Autonomous College Foundation Inc. of Isabela City', 'hei_code' => '15035', 'type_of_heis' => 'Public', 'city' => 'Isabela City', 'province' => 'Basilan', 'district' => 'Lone District (Basilan)'],
    ['hei_name' => 'Sulu College of Technology, Inc.', 'hei_code' => '15065', 'type_of_heis' => 'Private', 'city' => 'Sulu', 'province' => '', 'district' => 'UNKNOWN - verify'],
    ['hei_name' => 'Mindanao State University - Tawi-Tawi College of Technology and Oceonography', 'hei_code' => '15xxxx', 'type_of_heis' => 'Public', 'city' => 'Tawi-Tawi', 'province' => '', 'district' => 'UNKNOWN - verify'],
    ['hei_name' => 'J. H. Cerilles State College - Pagadian', 'hei_code' => 'NEW', 'type_of_heis' => 'Public', 'city' => 'Pagadian City', 'province' => 'Zamboanga del Sur', 'district' => '1st District, Zamboanga del Sur'],
    ['hei_name' => 'Zamboanga del Sur Provincial Government College - Margosatubig', 'hei_code' => 'NEW', 'type_of_heis' => 'Public', 'city' => '', 'province' => '', 'district' => 'UNKNOWN - verify'],
    ['hei_name' => 'Zamboanga del Sur Provincial Government College - Molave', 'hei_code' => 'NEW', 'type_of_heis' => 'Public', 'city' => 'Molave', 'province' => 'Zamboanga del Sur', 'district' => '1st District, Zamboanga del Sur'],
    ['hei_name' => 'Zamboanga del Sur Provincial Government College - Tabina', 'hei_code' => 'NEW', 'type_of_heis' => 'Public', 'city' => 'Tabina', 'province' => 'Zamboanga del Sur', 'district' => '2nd District, Zamboanga del Sur'],
    ['hei_name' => 'Philippine Malaya College, Inc.', 'hei_code' => 'NEW', 'type_of_heis' => 'Private', 'city' => 'Mampang', 'province' => 'Zamboanga City', 'district' => '2nd District, Zamboanga City'],
    ['hei_name' => 'Zamboanga del Sur Provincial Government College - Josefina', 'hei_code' => 'NEW-Jos', 'type_of_heis' => 'Public', 'city' => 'Josefina', 'province' => 'Zamboanga del Sur', 'district' => '1st District, Zamboanga del Sur'],
    ['hei_name' => 'Zamboanga del Sur Provincial Government College - Lapuyan', 'hei_code' => 'NEW-Lap', 'type_of_heis' => 'Public', 'city' => 'Lapuyan', 'province' => 'Zamboanga del Sur', 'district' => '2nd District, Zamboanga del Sur'],
    ['hei_name' => 'Zamboanga del Sur Provincial Government College - Mahayag', 'hei_code' => 'NEW-Mah', 'type_of_heis' => 'Public', 'city' => 'Mahayag', 'province' => 'Zamboanga del Sur', 'district' => '1st District, Zamboanga del Sur'],
    ['hei_name' => 'Zamboanga Peninsula Polytechnic State University - Malangas', 'hei_code' => 'NEW-Mal', 'type_of_heis' => 'Public', 'city' => '', 'province' => 'Zamboanga del Sur', 'district' => '2nd District, Zamboanga del Sur'],
    ['hei_name' => 'Zamboanga del Sur Provincial Government College - Midsalip', 'hei_code' => 'NEW-Mid', 'type_of_heis' => 'Public', 'city' => 'Midsalip', 'province' => 'Zamboanga del Sur', 'district' => '1st District, Zamboanga del Sur'],
    ['hei_name' => 'Zamboanga del Sur Provincial Government College - Ramon Magsaysay', 'hei_code' => 'NEW-Ram', 'type_of_heis' => 'Public', 'city' => 'Ramon Magsaysay', 'province' => 'Zamboanga del Sur', 'district' => '1st District, Zamboanga del Sur'],
    ['hei_name' => 'Zamboanga del Sur Provincial Government College - Tambulig', 'hei_code' => 'NEW-Tam', 'type_of_heis' => 'Public', 'city' => 'Tambulig', 'province' => 'Zamboanga del Sur', 'district' => '1st District, Zamboanga del Sur'],
    ['hei_name' => 'Zamboanga del Sur Provincial Government College - Tigbao', 'hei_code' => 'NEW-Tig', 'type_of_heis' => 'Public', 'city' => 'Tigbao', 'province' => 'Zamboanga del Sur', 'district' => '2nd District, Zamboanga del Sur'],
    ['hei_name' => 'Zamboanga del Sur Provincial Government College - Tukuran', 'hei_code' => 'NEW-Tuk', 'type_of_heis' => 'Public', 'city' => 'Tukuran', 'province' => 'Zamboanga del Sur', 'district' => '1st District, Zamboanga del Sur'],
    ['hei_name' => 'Zamboanga del Sur Provincial Government College - Vincenzo Sagun', 'hei_code' => 'NEW-Vin', 'type_of_heis' => 'Public', 'city' => 'Vincenzo Sagun', 'province' => 'Zamboanga del Sur', 'district' => '2nd District, Zamboanga del Sur'],
];
        foreach ($heis as $heiData) {
            // Use firstOrCreate to prevent creating duplicate records if you run the seeder again
            HEI::firstOrCreate(
                ['hei_name' => $heiData['hei_name']], // Find by name
                $heiData // Create with all data if not found
            );
        }
    }
}